In [1]:
import torch

print(torch.__version__)

1.11.0+cpu


In [10]:
x = torch.empty(1)
y = torch.empty(1)

print(x)
print(y)

tensor([0.])
tensor([9.1477e-41])


In [11]:
x = torch.empty(3)

print(x)

tensor([9.1477e-41, 0.0000e+00, 5.6052e-45])


In [12]:
x = torch.empty(2,5)

print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [13]:
x = torch.empty(2, 2, 3)

print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [14]:
x = torch.rand(1)
print(x)

tensor([0.7608])


In [15]:
print(torch.rand(2,3))

tensor([[0.5363, 0.9550, 0.6757],
        [0.2833, 0.1722, 0.6921]])


In [20]:
print(torch.rand(2,3, dtype=torch.float64))

tensor([[0.7175, 0.2815, 0.6698],
        [0.3889, 0.6029, 0.2042]], dtype=torch.float64)


In [23]:
print(torch.ones(2,3, dtype=torch.int))

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [24]:
print(torch.ones(2,3, dtype=torch.float64))

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [25]:
x = torch.tensor([1, 0.5])
print(x)
print(x.shape)

tensor([1.0000, 0.5000])
torch.Size([2])


In [26]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x+y)

tensor([[1.6939, 1.1599],
        [1.4602, 0.8375]])


In [28]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

print(x+y)

print(y.add_(x))
print(y)

tensor([[0.8713, 0.5807],
        [0.4150, 0.8539]])
tensor([[0.7645, 0.2439],
        [0.2516, 0.9650]])
tensor([[1.6358, 0.8246],
        [0.6666, 1.8189]])
tensor([[1.6358, 0.8246],
        [0.6666, 1.8189]])
tensor([[1.6358, 0.8246],
        [0.6666, 1.8189]])


In [34]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

print(y+x)

y+=x
print(y)

tensor([[0.1923, 0.1162],
        [0.8203, 0.8562]])
tensor([[0.9125, 0.1719],
        [0.7351, 0.0641]])
tensor([[1.1049, 0.2881],
        [1.5554, 0.9202]])
tensor([[1.1049, 0.2881],
        [1.5554, 0.9202]])


In [35]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x - y)
print(torch.sub(x,y))

tensor([[ 0.0023,  0.1327],
        [-0.4308,  0.8073]])
tensor([[ 0.0023,  0.1327],
        [-0.4308,  0.8073]])


In [36]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x * y)
print(torch.mul(x,y))

tensor([[0.6657, 0.1271],
        [0.4094, 0.6817]])
tensor([[0.6657, 0.1271],
        [0.4094, 0.6817]])


In [37]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x / y)
print(torch.div(x,y))

tensor([[ 1.8680,  0.5868],
        [13.6759, 12.9181]])
tensor([[ 1.8680,  0.5868],
        [13.6759, 12.9181]])


In [44]:
x = torch.rand(5,10)

print(x)

print(x[:, 0])

print(x[1, 0])

print(x[1, 0].item())

tensor([[0.8854, 0.3685, 0.5990, 0.0638, 0.9251, 0.0703, 0.2928, 0.9550, 0.9195,
         0.4407],
        [0.5401, 0.7549, 0.2166, 0.3995, 0.8255, 0.9197, 0.3671, 0.3497, 0.9908,
         0.6937],
        [0.0627, 0.0981, 0.2359, 0.5235, 0.4410, 0.1012, 0.0125, 0.7444, 0.8132,
         0.7597],
        [0.4919, 0.4358, 0.2311, 0.5395, 0.6858, 0.1351, 0.0725, 0.7313, 0.8071,
         0.9265],
        [0.0694, 0.9983, 0.5822, 0.1319, 0.5688, 0.8290, 0.3571, 0.6691, 0.4584,
         0.6429]])
tensor([0.8854, 0.5401, 0.0627, 0.4919, 0.0694])
tensor(0.5401)
0.5400557518005371


In [45]:
print(x.item())

ValueError: only one element tensors can be converted to Python scalars

In [50]:
x = torch.rand(4, 4)
print(x)

y = x.view(16)
print(y)

tensor([[0.8043, 0.4259, 0.7375, 0.7200],
        [0.2381, 0.7358, 0.7546, 0.6067],
        [0.2854, 0.5277, 0.4633, 0.8174],
        [0.7852, 0.5468, 0.3542, 0.4930]])
tensor([0.8043, 0.4259, 0.7375, 0.7200, 0.2381, 0.7358, 0.7546, 0.6067, 0.2854,
        0.5277, 0.4633, 0.8174, 0.7852, 0.5468, 0.3542, 0.4930])


In [53]:
x = torch.rand(4, 4)
print(x)

y = x.view(-1, 8)
print(y)
print(y.size())
print(y.shape)

tensor([[0.8743, 0.3542, 0.0560, 0.1719],
        [0.6600, 0.3342, 0.5785, 0.5582],
        [0.6538, 0.3718, 0.4810, 0.5081],
        [0.4321, 0.0909, 0.1119, 0.0465]])
tensor([[0.8743, 0.3542, 0.0560, 0.1719, 0.6600, 0.3342, 0.5785, 0.5582],
        [0.6538, 0.3718, 0.4810, 0.5081, 0.4321, 0.0909, 0.1119, 0.0465]])
torch.Size([2, 8])
torch.Size([2, 8])


In [52]:
x = torch.rand(4, 4)
print(x)

print(x.view(-1, 5))

tensor([[0.7946, 0.3328, 0.6826, 0.6507],
        [0.7243, 0.0192, 0.0576, 0.5428],
        [0.9471, 0.8587, 0.6991, 0.6652],
        [0.6117, 0.3952, 0.8485, 0.7493]])


RuntimeError: shape '[-1, 5]' is invalid for input of size 16

In [55]:
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [56]:
a = torch.ones(5)
b = a.numpy()

print(a)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
